version: 0.2

phases:
  build:
    commands:
    - echo "This is build phase... Zipping my webpage"
 
  post_build:
    commands:
    - echo "Deployed to S3"
    - aws s3 cp * s3://wasu-tcw-destination/vasu-demo/  
artifacts:
  files:
    - '**/*'
